//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtherColors.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorExtensions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorExtensions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OtherColors.Resources.ColorExtensions", typeof(ColorExtensions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bleu d&apos;or.
        /// </summary>
        internal static string OtherColors_ColorExtensions_GoldenBlue {
            get {
                return ResourceManager.GetString("OtherColors.ColorExtensions.GoldenBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vert d&apos;or.
        /// </summary>
        internal static string OtherColors_ColorExtensions_GoldenGreen {
            get {
                return ResourceManager.GetString("OtherColors.ColorExtensions.GoldenGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rouge doré.
        /// </summary>
        internal static string OtherColors_ColorExtensions_GoldenRed {
            get {
                return ResourceManager.GetString("OtherColors.ColorExtensions.GoldenRed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellblau.
        /// </summary>
        internal static string OtherColors_ColorExtensions_LightBlue {
            get {
                return ResourceManager.GetString("OtherColors.ColorExtensions.LightBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellgrün.
        /// </summary>
        internal static string OtherColors_ColorExtensions_LightGreen {
            get {
                return ResourceManager.GetString("OtherColors.ColorExtensions.LightGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hellrot.
        /// </summary>
        internal static string OtherColors_ColorExtensions_LightRed {
            get {
                return ResourceManager.GetString("OtherColors.ColorExtensions.LightRed", resourceCulture);
            }
        }
    }
}
